### ISSUE TITLE
v8bench/regexp is a benchmark from hell

### ISSUE THREAD

**Issue by maximecb** [higgsjs/Higgs#111]
This is the last/only V8 benchmark not working. This benchmark came from hell, and is an endless pit of bugs. Please help us fix all the bugs so that we may vanquish the demon once and for all.

**Comment by MartinNowak** [comment]
Have you thought about using http://dlang.org/phobos/std_regex.html?
It's reasonably fast in many cases, not sure if the overhead to call into the runtime is acceptable.

**Comment by maximecb** [comment]
I'm pretty sure the syntax is incompatible. Might be possible to translate, but that seems like a rather risky endeavor.

**Comment by MartinNowak** [comment]
Well the docs say `This library uses a remarkably common ECMAScript syntax flavor with the following extensions`. What do you say @DmitryOlshansky?

**Comment by DmitryOlshansky** [comment]
Syntax should be the same except for /<regex>/<flags> notation of JS. The only problem should be detecting and disabling syntax extensions not present in JS. I think Regex!wchar should fit just fine.

As for speed, I'd love to have more benchmarks to tune it.

**Comment by MartinNowak** [comment]
Sounds like we could kill 2 birds with one stone.
Looks fairly simple to disable the extensions, but they don't collide with anything, so leaving them in will hardly hurt anyone. Maybe we could add a flag or wrapper to std.regex for full ECMA compliant regexes.

**Comment by maximecb** [comment]
This isn't really something I want for Higgs, for a number of reasons:

1. I want to keep the implementation as self-hosted as possible, the interface with the host language as small as possible. I'll still want to keep the current implementation.

2. It's a bit of a hack, disguising the D regex engine.

3. It won't fix many of the regexp bugs we had/have, because they are not bugs in the regex engine itself.

4. I'm really not so sure there would be much of a speed gain. Calls into hosted D code are fairly slow. Strings need to be passed back and forth from the regex. There's quite a bit of overhead.

5. Even if there is a speed gain, we might still be quite far from V8's jitted regex engine, an order of magnitude slower. I think the only way to compete with them on regex performance is with a natively compiled JIT engine that is well interfaced with the Higgs JIT.

**Comment by DmitryOlshansky** [comment]
Feel free to do as you please. Regarding points raised:
1. Can't really argue against preferences.
2. In fact I plan to expose a feature to limit D regex to a given subset. Doesn't fell hackish at all.
3. What are they then? I'm ignorant of current bugs admittedly.
4. Slices ought to be cheap but I know nothing of higgs architecture.
5. In my tests most of gain is algorithmic improvements and better data-structures. JIT may help a lot though - interpreter loop dispatch is ~30% of run-time. However main gain is reducing a factor in front of these X%.

**Comment by MartinNowak** [comment]
Well your choice, it just looked like a good opportunity to improve two projects.

**Comment by maximecb** [comment]
There have been several bugs in the implementation of String.replace when using regexp arguments

Slices of JS strings to present them as D strings are going to be relatively cheap, but JS strings need to live in the JS heap, which requires copying. Sending a list of matches back into JS code is going to be pretty slow.

**Comment by etcimon** [comment]
> JS strings need to live in the JS heap, which requires copying. Sending a list of matches back into JS code is going to be pretty slow.

Unless you expose the JS heap to D. It should be straight-forward for JS to send a pointer to a pointer to an array of matches to a C fct which allocates it all properly using an `allocate` method ...?

**Comment by etcimon** [comment]
I was looking at the GC code, and to my surprise I saw the use of linked lists for layout out the virtual machine's functions and instructions internally. I doubt you often modify the ordering of these `IRBlock`/`IRInstr` objects frequently during the runtime of a program, so you're basically paying a very high price for iterating through it every time you run short on space. It reminds me of this read:

http://blog.davidecoppola.com/2014/05/20/cpp-benchmarks-vector-vs-list-vs-deque/

**Comment by maximecb** [comment]
The ordering of IR instructions is not changed often, but blocks are deleted often. I'm probably going to redesign the IR for more efficiency eventually. The focus will be on making the data structure as flat as possible to minimize allocations. That is currently where the most overhead lies, not in the traversal per-se.

**Comment by maximecb** [comment]
Closing this issue for now, will reopen a more specific one regarding string bugs.
