### ISSUE TITLE
lib/draw needs onClick callbacks for mouse events

### ISSUE THREAD

**Issue by maximecb** [higgsjs/Higgs#158]
The [draw library](https://github.com/maximecb/Higgs/blob/master/source/lib/draw.js) already has the possibility of registering an onKeypress event to handle keyboard events. It would be desirable to also have an onClick function to be able to capture mouse clicks. This should ideally supply the registered callback function with the mouse x,y coordinates (relative to the upper-left corner of the drawable canvas) as well as the name of the button pressed.

@tach4n your input is welcome.

**Comment by bFraley** [comment]
github.com/bFraley/Higgs/tree/mouse

Try 'drawing-mod.js' in examples. You'll see that mouse click and motion events are working. There's some logging and print statements to be removed before finalizing any of these changes. Hopefully they help narrow down getting at the xy coordinates. @tach4n , can you narrow down this down? 
@maximecb  It's been a long time on this, let me know if my example works on your machine too.

**Comment by maximecb** [comment]
@tach4n, if you could take a look at this I'd really appreciate it, as having mouse click support in the drawing lib would be most awesome.

Ideally, I'd like to have some miminmal support for nested structs and a proper fix, but in the worst case we could directly read at the required offset to get the data we need.

**Comment by tach4n** [comment]
@maximecb @bfraley cool!

I should be able to take a look today, though I dunno how much time I can devote to it. Definitely can do more over the weekend. I'll be in the IRC.

**Comment by bFraley** [comment]
@tach4n  Thanks, hopefully you see something simple I'm missing. I will be a bit more active on Higgs again, and will be on irc this weekend.

**Comment by bFraley** [comment]
PR #193 exposes x xy coords `mouseX` and `mouseY` on all motion and click events.

I'll be working on other event properties like:
-Which mouse button was pressed?
-Is it held, or released. Was it dragged?
-Mouse coordinates for onKeyPress

**Comment by maximecb** [comment]
I would add separate onMouseDown and onMouseUp callbacks, to sort of mirror the web APIs.

**Comment by bFraley** [comment]
Is it safe to say this is closed?

**Comment by maximecb** [comment]
Yes sir.
