### ISSUE TITLE
Regex.prototype.test returns null instead of false

### ISSUE THREAD

**Issue by SBSTP** [higgsjs/Higgs#174]
When the string does not match the regex, it returns null instead of false. It causes issues when you use strict equality.
```js
> /abc/.test('d')
null
> /[0-9]/.test('a')
null
> /.*/.test('')
true
```

**Comment by SBSTP** [comment]
Looks like a fairly easy fix: https://github.com/higgsjs/Higgs/blob/master/source/stdlib/regexp.js#L2713

**Comment by maximecb** [comment]
Can you make a PR for the fix and an additional test that catches it, under tests/xx-stdlib/regexp :D

**Comment by SBSTP** [comment]
Sure thing!
