### ISSUE TITLE
Reserving IRBlock[]'s capacity

### ISSUE THREAD

**Issue by rsw0x** [higgsjs/Higgs#197]
Hi, I'm collecting GC sample data for D with Higgs and happened across 

https://github.com/higgsjs/Higgs/blob/master/source/ir/livevars.d#L290

after a few tests, I noticed that the length of the array usually maxes out in single digits and commenting out the line made all the benchmarks I tested run ~3-10% faster, and peak memory usage was about 25-30mb less on average. For example, with it commented out the Chess benchmark requests 46518 KiB less memory from the GC(my calculation), and took 59ms less total time according to Higg's perf_stats flag.

I'm unsure if this breaks anything, so I just thought I'd submit an issue.

Bye.

**Comment by maximecb** [comment]
Thanks. I'll make the change.

If you want to test for breakage, you can run `make test`.
