### ISSUE TITLE
Windows support in Higgs

### ISSUE THREAD

**Issue by lygstate** [higgsjs/Higgs#201]

**Comment by bFraley** [comment]
Higgs is primarily designed with and for POSIX operating systems. There's been some discussion on supporting Windows in the past, but it was agreed to be a daunting task that will surely spawn it's own set of bugs specific to supporting Windows.

Even if someone got the VM to build, compile code, and execute Higgs programs in a Windows environment, there is no one to maintain that support . You would have to thoroughly understand the VM's architecture and design, every feature of Higgs' JavaScript implementation, and be ready to diagnose numerous Windows system errors. I'm not saying it's impossible, but that the amount of research and testing involved is somewhat infeasible to expect to get accomplished.

**Comment by lygstate** [comment]
I would working on it, so don't close this.

**Comment by lygstate** [comment]
@bFraley @maximecb are that means refuse other people to add windows support for higgs

**Comment by maximecb** [comment]
You can fork Higgs and add Windows support if you want, but we won't support it in this repository.

**Comment by lygstate** [comment]
@maximecb I means if I add windows support in Higgs, is that possible to merge back into this repo?
