### ISSUE TITLE
Suggest move benchmarks out of Higgs source  tree.

### ISSUE THREAD

**Issue by lygstate** [higgsjs/Higgs#204]
It's too big, and making clone Higgs being time consuming.

**Comment by bFraley** [comment]
Not a bad idea if your resources are very limited in some way, but this issue isn't relevant to Higgs' development. If you want a Higgs source tree without the benchmark files, you could fork, edit accordingly, and clone your own.

**Comment by maximecb** [comment]
I think it's convenient to have the benchmarks in the same source tree.
