### ISSUE TITLE
DMD Deprecated Modules

### ISSUE THREAD

**Issue by bFraley** [higgsjs/Higgs#207]
I'm running a fresh DMD install, version (2.071.0)
It seems multiple D modules are moved/renamed.

@maximecb Is this as simple as updating the module names, or may there be more complex side effects of doing so?
 
```
runtime/vm.d(41): Deprecation: module std.c.string is deprecated - Import core.stdc.string instead
runtime/gc.d(41): Deprecation: module std.c.stdlib is deprecated - Import core.stdc.stdlib or core.sys.posix.stdlib instead
runtime/gc.d(42): Deprecation: module std.c.string is deprecated - Import core.stdc.string instead
runtime/string.d(40): Deprecation: module std.c.string is deprecated - Import core.stdc.string instead
jit/ops.d(42): Deprecation: module std.c.math is deprecated - Import core.stdc.math instead
main.d(41): Deprecation: module std.c.string is deprecated - Import core.stdc.string instead
main.d(42): Deprecation: module std.c.stdlib is deprecated - Import core.stdc.stdlib or core.sys.posix.stdlib instead
ir/ast.d(360): Deprecation: runtime.vm.stats is not visible from module ast
stats.d(192): Deprecation: function std.datetime.Clock.currAppTick is deprecated - Use core.time.MonoTime instead. See currAppTick's documentation for details.

```

**Comment by maximecb** [comment]
It might well be as simple as updating the module names.

**Comment by bFraley** [comment]
Almost done with this, dropping some notes here for now:

```
ir/ast.d(360): Deprecation: runtime.vm.stats is not visible from module ast
stats.d(193): Deprecation: module core.time is not accessible here, perhaps add 'static import core.time;'
stats.d(193): Error: cannot implicitly convert expression (MonoTimeImpl(0L)) of type MonoTimeImpl!cast(ClockType)0 to ulong

```

**Comment by bFraley** [comment]
@maximecb I'm trying to work these deprecations out, but I'm starting realize the replacement of currAppTick may of caused many issues for Higgs. I'll keep trying to work through it. 

Check out: https://dlang.org/library/core/time/mono_time_impl.html
I'm not totally sure how and where you've used timing functions that rely on currAppTick,
so let me know if you have a straight forward solution.

**Comment by maximecb** [comment]
Hi Brett,

I'm sorry for not answering you faster. I've been really busy with work and also preparing a talk about Higgs and my PhD work next Wednesday in Rome (ECOOP 2016).

Higgs uses the curAppTick to get a microsecond counter in order to approximately measure compilation time. It might also be used to implement Date.getTime (callable from JavaScript). I would try to make it use MonoTime instead. I just hope the resolution is high enough.

Try to print out ticksPerSecond to find out what resolution you get on a Linux machine:
https://dlang.org/library/core/time/mono_time_impl.ticks_per_second.html

**Comment by bFraley** [comment]
Okay great!  Congrats on that btw!  Remember, 'when in Rome...'

**Comment by bFraley** [comment]
Closing this issue with #208 and opening convert 'currAppTick timer to use MonoTime methods'
